# specify the node base image with your desired version node:<version>
FROM node:alpine
# replace this with your application's default port
EXPOSE 3000
WORKDIR /usr/src/app

# to add global yarn packages
# RUN yarn global add ${PACKAGE}@${VERSION}